linters:
  enable-all: true
  disable:
    - gci
    - exhaustivestruct
    - exhaustruct
    - interfacer
    - golint
    - maligned
    - scopelint
    - cyclop
    - prealloc
linters-settings:
  ireturn:
    allow:
      - anon
      - error
      - empty
      - stdlib
      - github.com/charmbracelet/bubbletea.Model