name: Lint
on: [pull_request]
permissions:
  contents: read
  pull-requests: read
  checks: write
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.23.0'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60